version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8002:8002"
    volumes:
      - ./api.py:/app/api.py
      - ./requirements.txt:/app/requirements.txt
      - type: bind
        source: ../models/
        target: /app/models/
    environment:
      - MODEL_PATH=/app/models/rf_model_20250724_1608.pkl # Ensure this matches the model copied
    restart: unless-stopped