FROM python:3.10-slim

WORKDIR /app

# Install curl for health checks
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api.py .
COPY models/ ./models
COPY dags/ ./dags

EXPOSE 8002

CMD ["gunicorn", "-w 4", "-k uvicorn.workers.UvicornWorker", "api:app", "--bind", "0.0.0.0:8002", "--log-level", "debug"]