global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'financial-api'
    static_configs:
      - targets: ['financial-api:8002']
    metrics_path: '/metrics'
    scrape_interval: 15s
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']